### ISSUE TITLE
This node error

### ISSUE THREAD

**Issue by SoftiGest** [willnode/Nottorus-Unnoficial-Patches#1]
Trying to add a THIS node but no pin to connect :(

**Comment by willnode** [comment]
Clarification?

'this' doesn't work unless you're recompile after new script creation.

**Comment by SoftiGest** [comment]
Sorry, i'm stupid, i've missing to compile to get This working on new script :/

**Comment by willnode** [comment]
Yeah no problem at all. This is one of UX failure that I want to fix 😄

**Comment by SoftiGest** [comment]
😄 

Many thanks for your job, I will try Nottorus in my project and if I can help you to improve it, it's with pleasure ;)
